# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "56505304f3c96a93db57dbec3fda07dd"
name = "StickyCart"
application_url = "https://stickycartboost-33f7fb3bfb6f.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
uri = "/webhooks/customers/data_request"
compliance_topics = ["customers/data_request"]

[[webhooks.subscriptions]]
uri = "/webhooks/customers/redact"
compliance_topics = ["customers/redact"]

[[webhooks.subscriptions]]
uri = "/webhooks/shop/redact"
compliance_topics = ["shop/redact"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://stickycartboost-33f7fb3bfb6f.herokuapp.com/auth/callback",
  "https://stickycartboost-33f7fb3bfb6f.herokuapp.com/auth/shopify/callback",
  "https://stickycartboost-33f7fb3bfb6f.herokuapp.com/api/auth/callback",
]

[app_proxy]
url = "https://stickycartboost-33f7fb3bfb6f.herokuapp.com/proxy"
subpath = "Sticky"
prefix = "apps"
