# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c23e9fe0713ccd6c1eff49729441698d"
name = "sticky2.0"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"


  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products"

[auth]
redirect_urls = [
  "https://stickycartboost-33f7fb3bfb6f.herokuapp.com/auth/callback",
  "https://stickycartboost-33f7fb3bfb6f.herokuapp.com/auth/shopify/callback",
  "https://stickycartboost-33f7fb3bfb6f.herokuapp.com/api/auth/callback"
]

[app_proxy]
url = "https://stickycartboost-33f7fb3bfb6f.herokuapp.com/proxy"
subpath = "Sticky"
prefix = "apps"

